cookie:
  expiry_days: 1
  key: s6,W![PC**lSTY4~v\1G
  name: preregistertest
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$dncJFE5FkV4pqi77XG4/puPCTzTViWrkfpYC/K.hid38.CBtgFKoa
      roles:
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$Q6mQ14y5X4BwZN126mpMj.LCnVV9f7GqgwZXfzzAd1DBRgtjf2CL2
      roles:
      - viewer
    zetter:
      email: zetter.vitrolic@gmail.com
      failed_login_attempts: 0
      first_name: zettus
      last_name: zettas
      logged_in: false
      password: $2b$12$.bBIqmKLDDqxbJox1mDlsuWQQHPCj0.PnA2ZvbZUDlpLIxtmj6Gae
      roles:
      - admin
      - editor
      - viewer
    zettos:
      email: kovaseros@gmail.com
      failed_login_attempts: 2
      first_name: zettis
      last_name: zettos
      logged_in: false
      password: $2b$12$uRgKiKdLf7vBldX/s8DFcuUw/RihXtgaQ7DQYwhONnKmZpP5b1Yq.
      password_hint: rfrf
      roles: null
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
  - zetter.vitrolic@gmail.com
